#!/usr/bin/env bash
# Keycloak host setup, run by infra-apply before `docker compose up`. Idempotent.
#   - generates /etc/infra/keycloak.env (admin + database passwords) once
#   - installs the nightly database dump timer (bin/keycloak-backup)
set -euo pipefail

ENV_FILE=/etc/infra/keycloak.env

if [[ ! -f $ENV_FILE ]]; then
  admin_password=$(head -c 24 /dev/urandom | base64 | tr -d '/+=')
  db_password=$(head -c 24 /dev/urandom | base64 | tr -d '/+=')
  install -d -m 0755 /etc/infra
  install -m 0600 /dev/null "$ENV_FILE"
  cat >"$ENV_FILE" <<ENV
# Generated by services/keycloak/setup.sh. Used by both containers.
KC_BOOTSTRAP_ADMIN_USERNAME=bootstrap-admin
KC_BOOTSTRAP_ADMIN_PASSWORD=$admin_password
KC_DB_PASSWORD=$db_password
POSTGRES_PASSWORD=$db_password
ENV
  echo "keycloak: created $ENV_FILE"
  echo "keycloak: temporary admin — user: bootstrap-admin  password: $admin_password"
  echo "keycloak: log in at https://auth.kaptajnkasper.net/admin, create your own admin user, then delete bootstrap-admin"
fi

install -m 0755 -o root -g root /srv/infra/bin/keycloak-backup /usr/local/sbin/keycloak-backup

cat >/etc/systemd/system/keycloak-backup.service <<'UNIT'
[Unit]
Description=Dump the Keycloak database to /var/backups/keycloak

[Service]
Type=oneshot
ExecStart=/usr/local/sbin/keycloak-backup
UNIT
cat >/etc/systemd/system/keycloak-backup.timer <<'UNIT'
[Unit]
Description=Nightly Keycloak database dump

[Timer]
OnCalendar=*-*-* 03:30:00
Persistent=true

[Install]
WantedBy=timers.target
UNIT
systemctl daemon-reload
systemctl enable -q --now keycloak-backup.timer
